### PR TITLE
Update sticky table header style in styles.css

### PR DESCRIPTION
**Pull request by asabuncuoglu13**
**Current behaviour of the web page:**

The header moves all the way up with the content, which makes it hard to view features for the models.

**Suggested behaviour:**

Sticky header position fixed at the top when moved.

### CODE REVIEW

**Review by mdingemanse — APPROVED** [review]
Interesting. Thanks for the contribution! Will merge this in and then check across device types and browsers

**Comment by mdingemanse** [comment]
Hey, thanks — works for me on desktop in Firefox. Not on mobile AFAICS and my HTML/CSS is too rusty to figure out how/why. Do you have capacity to test this? Not a breaking issue as your contribution is a great improvement on desktop anyway!

**Comment by asabuncuoglu13** [comment]
Hey, no worries! I also checked it now and encountered the same issue. The problem is the ```overflow-x``` behaviour of ```div#included-table``` (when the width is less than 1200px) breaks the sticky header position. I think you can safely remove the ```overflow-x: auto``` line. Because you are already resizing the entire table for responsive behaviour, so you expect to see the same overflow behaviour with the desktop view.

**Comment by mdingemanse** [comment]
[Implemented](https://github.com/opening-up-chatgpt/opening-up-chatgpt.github.io/commit/4b90b787de673b2488684251586d727ade7930c4) this. Not entirely happy with how it looks on mobile (at least Firefox @ Android) but then again the table was never really highly accessible to begin with.

**Pull request merged**
